[package]
name = "td_tool_agent"
version = "0.1.0"
edition = "2024"

[dependencies]
td_tool_model={path ="../td_tool_model"}
reqwest = { version = "0.12.28" , features = ["json"]}
tokio ={version =  "1.48.0", features = ["full"]}
serde_json = "1.0.148"